apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::832115041474:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1QQTEB2CGGKJ8
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::832115041474:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-20T11:38:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1344"
  uid: 62d313ce-09b8-4ab8-939f-67fd88bac08c
